export {
    SET_CAMEL_CASE,
    SET_CONSTANT_CASE,
    SET_DOT_CASE,
    SET_HEADER_CASE,
    SET_LOWER_CASE,
    SET_LOWER_FIRST_CASE,
    SET_PASCAL_CASE,
    SET_PATH_CASE,
    SET_PARAM_CASE,
    SET_SENTENCE_CASE,
    SET_SNAKE_CASE,
    SET_SWAP_CASE,
    SET_TITLE_CASE,
    SET_UPPER_CASE,
    SET_UPPER_FIRST_CASE
} from '../common-actions';

export const COPY_TEXT = 'COPY_TEXT';
